### ISSUE TITLE
Different results with flutter run and building release

### ISSUE THREAD

**Issue by bas24** [imloama/dart-stellar-hd-wallet#1]
Hi, could you please give an insight why I'm getting different results decoding mnemonic in debug mode and building release?

final wallet = StellarHDWallet.fromMnemonic(mnemonic);
final keyPair = wallet.getKeyPair();

gives me different results with flutter run and testing release. Tried with Android.

**Comment by imloama** [comment]
I test it in my project [maxtoken], you are right.
But the two modes has the same seed, so it seems the stellar sdk goes wrong.
I will test more.

**Comment by bas24** [comment]
Yeah, the same for Android and iOS.

**Comment by imloama** [comment]
@bas24 update your flutter to 1.7.x，I run tests and it works well.
My test environments:
- Flutter 1.7.8+hotfix.4 • channel stable • https://github.com/flutter/flutter.git
- Framework • revision 20e59316b8 (2 weeks ago) • 2019-07-18 20:04:33 -0700
- Engine • revision fee001c93f
- Tools • Dart 2.4.0
